<div class="container">
	<form class="form-horizontal" method="POST" enctype="multipart/form-data">
	    <fieldset>
	        <!-- Form Name -->
	        <legend>Create User</legend> <!-- Text input-->
	        <input type="hidden" name="user_id" value="<?php echo $user['user_id']; ?>" />
	        <div class="row">
	        	<div class="col-md-6 col-lg-6">
			        <div class="form-group">
			            <label class="col-md-3 control-label" for=
			            "user_firstname">First Name</label>

			            <div class="col-md-8">
			                <input class="form-control input-md" id="user_firstname" name=
			                "user_firstname" placeholder="Juan" required="" value="<?php echo $user['user_firstname']; ?>" type=
			                "text">
			            </div>
			        </div><!-- Text input-->

			        <div class="form-group">
			            <label class="col-md-3 control-label" for=
			            "user_lastname">Last Name</label>

			            <div class="col-md-8">
			                <input class="form-control input-md" id="user_lastname" name=
			                "user_lastname" placeholder="dela Cruz" required="" value="<?php echo $user['user_lastname']; ?>" type=
			                "text">
			            </div>
			        </div>

			        <div class="form-group">
			            <label class="col-md-3 control-label" for=
			            "user_birth">Birthdate</label>

			            <div class="col-md-8">
			                <input class="form-control input-md" id="user_birth" name=
			                "user_birth" placeholder="dela Cruz" required="" value="<?php echo $user['user_birth']; ?>" type=
			                "text">
			            </div>
			        </div><!-- Button -->
			    </div>
			    <div class="col-md-6 col-lg-6">
			        <div class="form-group">
			            <label class="col-md-3 control-label" for=
			            "user_email">Email</label>

			            <div class="col-md-8">
			                <input class="form-control input-md" id="user_email" name=
			                "user_email" placeholder="juandela@cruz.com" required="" value="<?php echo $user['user_email']; ?>" type=
			                "email">
			            </div>
			        </div><!-- Text input-->

			        <div class="form-group">
			            <label class="col-md-3 control-label" for=
			            "item_serial">Gender</label>

			            <div class="col-md-8">
							<select class="form-control" name="user_gender">
								<option value="male"<?php echo $user['user_gender']=='male'? ' selected' : ''; ?>>Male</option>
								<option value="female"<?php echo $user['user_gender']=='female'? ' selected' : ''; ?>>Female</option>
							</select>
			            </div>
			        </div><!-- Button -->
			        <div class="form-group">
						<label class="col-md-3 control-label" for="user_photo">Image</label>
						<div class="col-md-8">
							<input id="user_photo" name="user_photo" class="input-file" type="file">
							<?php if(strlen($user['user_photo'])) : ?>	
								<img style="margin-top: 10px" src="/image/user/<?php echo $user['user_id']; ?>" height="75"/>
							<?php endif; ?>
						</div>
					</div>
			    </div>
		    </div>

		    <div class="row">
	        	<div class="col-md-6 col-lg-6 col-md-offset-6 col-lg-offset-6">
	        		<button class="btn btn-primary" id="submit" name="submit">Submit</button>
	        	</div>
	        </div>
	    </fieldset>
	</form>
</div>

<script type="text/javascript">
	$('#user_birth').datepicker({
	    format: "yyyy-mm-dd",
	    weekStart: 0,
	    startView: 2
	});
</script>