<div class="container">
	<form class="form-horizontal" method="POST" enctype="multipart/form-data">
	    <fieldset>
	        <!-- Form Name -->
	        <legend>Edit Location - <?php echo $location['location_name']; ?></legend> <!-- Text input-->
	        <input type="hidden" name="location_id" value="<?php echo $location['location_id']; ?>" />
	        <div class="form-group">
	            <label class="col-md-4 control-label" for=
	            "location_name">Name</label>

	            <div class="col-md-6">
	                <input class="form-control input-md" id="location_name" name=
	                "location_name" placeholder="Location Name" required="" type=
	                "text" value="<?php echo $location['location_name']; ?>">
	            </div>
	        </div><!-- Text input-->

	        <div class="form-group">
	            <label class="col-md-4 control-label" for=
	            "location_serial">Id</label>

	            <div class="col-md-6">
	                <input class="form-control input-md" id="location_serial" name=
	                "location_serial" placeholder="Unique Id" required="" type=
	                "text" value="<?php echo $location['location_serial']; ?>">
	            </div>
	        </div><!-- Button -->

	        <div class="form-group">
	            <label class="col-md-4 control-label" for=
	            "location_address">Address</label>

	            <div class="col-md-6">
	                <textarea class="form-control input-md" id="location_address" name=
	                "location_address" placeholder="Full Address" required="" ><?php 
	                echo $location['location_address']; ?></textarea>
	            </div>
	        </div><!-- Button -->

			<!-- File Button --> 
			<div class="form-group">
				<label class="col-md-4 control-label" for="location_image">Image</label>
				<div class="col-md-4">
					<input id="location_image" name="location_image" class="input-file" type="file">
					<?php if(strlen($location['location_image'])) : ?>	
							<img style="margin-top: 10px" src="/image/location/<?php echo $location['location_id']; ?>" height="75"/>
					<?php endif; ?>
				</div>
			</div>

	        <div class="form-group">
	            <div class="col-md-offset-4 col-md-6">
	                <button class="btn btn-primary" id="submit" name=
	                "submit">Submit</button>
	            </div>
	        </div>
	    </fieldset>
	</form>
</div>