<div class="container">
	<table class="table">
		<thead>
			<tr>
				<th>Image</th>
				<th>Name</th>
				<th>Serial</th>
				<th>Created</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($items as $item): ?>
				<tr>
					<td><?php if(strlen($item['item_image'])) : 
					?>	<img src="/image/item/<?php echo $item['item_id']; ?>" height="50"/> <?php
						endif;
					?></td>
					<td><?php echo $item['item_name']; ?></td>
					<td><?php echo $item['item_serial']; ?></td>
					<td><?php echo $item['item_created']; ?></td>
					<td>
						<a href="/item/edit/<?php echo $item['item_id']; ?>" class="btn btn-primary">
							<i class="fa fa-edit"></i>
						</a>
						<a href="?delete=<?php echo $item['item_id']; ?>" class="btn btn-danger">
							<i class="fa fa-trash-o"></i>
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>