<div class="container">
	<table class="table">
		<thead>
			<tr>
				<th>Image</th>
				<th>Name</th>
				<th>Email</th>
				<th>Gender</th>
				<th>Birthdate</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($users as $user): ?>
				<tr>
					<td><?php if(strlen($user['user_image'])) : 
					?>	<img src="/image/user/<?php echo $user['user_id']; ?>" height="50"/> <?php
						endif;
					?></td>
					<td><?php echo $user['user_firstname'].' '.$user['user_lastname']; ?></td>
					<td><?php echo $user['user_email']; ?></td>
					<td><?php echo $user['user_gender']; ?></td>
					<td><?php echo $user['user_birth']; ?></td>
					<td>
						<a href="/user/edit/<?php echo $user['user_id']; ?>" class="btn btn-primary">
							<i class="fa fa-edit"></i>
						</a>
						<a href="?delete=<?php echo $user['user_id']; ?>" class="btn btn-danger">
							<i class="fa fa-trash-o"></i>
						</a>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>